spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:root@localhost:27017/bookingapp?authSource=admin

  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: postgres
    hikari:
      schema: booking_app
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS booking_app

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
    generate-ddl: false

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:changelog_init.xml
    default-schema: booking_app

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: StatisticGroup

app:
  jwt:
    secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    expireToken: 60m
    expireRefreshToken: 190m
  kafka_topics:
    registration-user-topic: "registration-user"
    booking-room-topic: "booking-room"
  statistic:
    source: src/main/resources/statistic
    registration-user-information-path: src/main/resources/statistic/registrationUser.csv
    booking-room-information-path: src/main/resources/statistic/bookingRoomInformation.csv

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"
