version: '3'
services:
  postgers:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
